name = "ainan-studio-backend"
main = "server-workers.js"
compatibility_date = "2024-01-01"

[env.production]
name = "ainan-studio-backend-prod"

# Environment variables
[vars]
JWT_SECRET = "your-super-secret-jwt-key-here"
ADMIN_EMAIL = "admin@ainanstudio.com"
ADMIN_PASSWORD = "admin123"
NODE_ENV = "production"

# KV Namespace for storing bookings and unavailable dates
[[kv_namespaces]]
binding = "BOOKINGS_KV"
id = "27c146c3d7d841ff99484b4f5e35bb33"
